import:
 - ~/.config/alacritty/dracula.yml
font:
  size: 13
  normal:
    family: SauceCodePro Nerd Font
    style: Regular
window:
  decorations:
    Buttonless
  title:
    Foo
env:
  TERM: xterm-256color
