import = ["/Users/scotthudson/.config/alacritty/dracula.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[window]
decorations = "Buttonless"
option_as_alt = "Both"
title = "Foo"
